config/routes.rb
Rails.application.routes.draw do

 root 'pictures#index'
 resources :users do
    resources :pictures
 end

 resources :sessions, only: [:new, :create]

  delete '/logout' => 'sessions#destroy', as: :logout
  resources :pictures, only: [:destroy]
 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/picture.rb
class Picture < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    has_many :pictures, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def authorize
    unless logged_in?
      redirect_to new_session_path
    end
  end

end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  def index
  end

  def show
    @picture = Picture.find(params[:id])
  end

  def new
    @picture = Picture.new

  end

  def create
    @picture = Picture.new(picture_params)
    @picture.user = current_user
    if @picture.save
      redirect_to user_path(current_user)
    end

  end

  def edit
    @picture = Picture.new
    @picture = Picture.find(params[:id])

  end

  def update
    @picture = Picture.find(params[:id])  
    @picture.user = current_user
    if @picture.update(picture_params)
      redirect_to user_path(current_user)
    end
  end

  def destroy
    @picture = Picture.find(params[:id])
    @picture.user = current_user
    if @picture.destroy
      redirect_to user_path(current_user)
   
    end

  end

  private
  def picture_params
    params.require(:picture).permit(:url, :location, :caption, :body, :user_id)
  end
  
end

app/controllers/pitcures_controller.rb
class PitcuresController < ApplicationController
  def index
  end

  def show
    @picture = Picture.new
  end

  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    
  end

  def create
    @user = User.find_by_email(params[:email])
    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      flash[:danger] = "Oooops! Email or username is incorrect. Please try again!"
      redirect_to new_session_path
    end
  end

  #logout
  def destroy 
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :authorize, only: [:show]

  def index
    @users = User.all
    @pic = Picture.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create

   @user = User.new(user_params)
   if @user.save
    redirect_to new_session_path
   else
    flash[:danger] = "Oh sanp! Password is not match! Please try again."
    redirect_to new_user_path
   end
  end

  def edit
  end

  def update
  end

  def destroy   
    #delete the cookie and log the user out 
    #in the user controller for destroy.
    @user = current_user
    session[:user_id] = nil
    if @user.destroy
      redirect_to root_path
    end    
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pitcures_helper.rb
module PitcuresHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Photomap</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">

  </head>

  <body>

<%= render 'partials/navbar' %>
  <div class="container-fluid">

  

  
    <!--<% if logged_in? %>
      Signed in As: <%= current_user.name%>
      <%= link_to('Logout', logout_path, {method: 'delete'})%>
     
    <% else %>
	    <%= link_to("Login", new_session_path) %>
    <% end %>
  -->
    <%= yield %>

    </div>
  </body>

</html>

app/views/partials/_navbar.html.erb
<div class="top-bar"></div>
<div class="container-fluid" class="link-to">
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar" href="/" ><img src="photomap-logo.png" width="60" height="60" alt="" ></a>
  <a class="navbar-brand" href="/" style="font-size: 28px;">Photomap</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav" style="float:right;">
      <a class="nav-item nav-link active" href="/users" style="color:rgb(244, 68, 68)">Discover <span class="sr-only">(current)</span></a>
      <a class="nav-item nav-link disabled" href="#">
        <% if logged_in? %>
        Hello!<%= link_to current_user.name, user_path(current_user), {:class =>"nav-item nav-link"}%>
        <%= link_to('Logout', logout_path, {method: 'delete', :class =>"nav-item nav-link"})%>
     
        <% else %>
          <a class="nav-item nav-link", href="/users/new">Sign up with email</a>

	        <%= link_to("Login", new_session_path, {:class =>"nav-item nav-link"}) %>
        <% end %>
      </a>
    </div>
  </div>
</nav>
</div>

app/views/pictures/create.html.erb
<h1>Pitcures#create</h1>
<p>Find me in app/views/pitcures/create.html.erb</p>

app/views/pictures/destroy.html.erb
<h1>Pitcures#destroy</h1>
<p>Find me in app/views/pitcures/destroy.html.erb</p>

app/views/pictures/edit.html.erb
<div class="container">
<%= image_tag(@picture.url, height: 'auto', width: '100%') %>

<%= form_for [current_user, @picture], :html => {class: 'new_user form-horizontal'} do |f| %>
    <div class="row" style="margin:30px 0px 30px 0px"><legend class="col-md-4 col-md-offset-4">Edit My Photomap</legend></div>
    <fieldset>
        <div class="form-group">
            <%= f.label :image, 'Image URL*', class: 'col-md-4 control-label' %>
            <div class="col-md-5">
                <%= f.text_field :url, class: 'form-control' %>
            </div>
        </div>
        <div class="form-group">
            <%= f.label :location, 'Location*', class: 'col-md-4 control-label' %>
            <div class="col-md-5">
                <%= f.text_field :location, class: 'form-control' %>
            </div>
        </div>
        <div class="form-group">
            <%= f.label :caption, 'Caption*', class: 'col-md-4 control-label' %>
            <div class="col-md-5">
                <%= f.text_field :caption, class: 'form-control' %>
            </div>
        </div>
        <div class="form-group">
            <%= f.label :body, 'Notes*', class: 'col-md-4 control-label' %>
            <div class="col-md-5">
                <%= f.text_field :body, class: 'form-control' %>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-8 col-md-offset-4">
                <%= f.submit 'Update it!', class: 'btn btn-dark' %>
            </div>
        </div>
    </fieldset>
    <% if flash[:danger] %>
    <div class="alert alert-danger">
        <%= flash[:danger] %>
    </div>
<% end %>
<% end %>
</div>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>

app/views/pictures/index.html.erb
<div>
<h1 class="lead" style="font-size: 50px; top: 30%; left: 10%; position: fixed;"><img src="/photomap-logo.png" width="60" height="60" alt="" style="vertical-align: text-bottom;">Exploring the world in one place...</h1>
</div>
<div class="container-fluid" class="img-fluid" alt="Responsive image" style="opacity: 0.6;">
<%= link_to image_tag('https://i.imgur.com/sdXPtfb.jpg', height: 'auto', width: '100%',), users_path %>
</div>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>

app/views/pictures/new.html.erb
<div class="container">
<%= form_for [current_user, @picture], :html => {class: 'new_user form-horizontal'} do |f| %>
    <div class="row" style="margin:10px 0px 30px 0px"><legend class="col-md-4 col-md-offset-4">Adding New Photo to My Photomap</legend></div>
    <fieldset>
        <div class="form-group">
            <%= f.label :image, 'Image URL*', class: 'col-md-4 control-label' %>
            <div class="col-md-5">
                <%= f.text_field :url, class: 'form-control' %>
            </div>
        </div>
        <div class="form-group">
            <%= f.label :location, 'Location*', class: 'col-md-4 control-label' %>
            <div class="col-md-5">
                <%= f.text_field :location, class: 'form-control' %>
            </div>
        </div>
        <div class="form-group">
            <%= f.label :caption, 'Caption*', class: 'col-md-4 control-label' %>
            <div class="col-md-5">
                <%= f.text_field :caption, class: 'form-control' %>
            </div>
        </div>
        <div class="form-group">
            <%= f.label :body, 'Notes*', class: 'col-md-4 control-label' %>
            <div class="col-md-5">
                <%= f.text_field :body, class: 'form-control' %>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-8 col-md-offset-4">
                <%= f.submit 'Add My Picture!', class: 'btn btn-dark' %>
            </div>
        </div>
    </fieldset>
    
<% end %>
</div>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>

app/views/pictures/show.html.erb
<div class="container">
<%= image_tag(@picture.url, height: 'auto', width: '100%') %>
<div style="margin:10px 0px 30px 0px">
<% if @picture.user == current_user %>
    <button type="button" class="btn btn-light" >   
      <%= link_to "Edit", edit_user_picture_path(current_user, @picture),{:class => "link-to"} %>
    </button>
<% end %>

<% if @picture.user == current_user %>
    <button type="button" class="btn btn-light" >   
      <%= link_to "Go Back", user_path(current_user, @picture), {:class => "link-to"} %>
    </button>
<% end %>

<% if @picture.user == current_user %>
    <button type="button" class="btn btn-light" style="float:right;"> 
      <%= link_to "Delete", picture_path(@picture), method: "delete", data: {confirm: "Are you sure you wnat to delete this photo?"}, :class => "link-to" %>
    
<% end %>
</button>
</div>
<h4 class="lead" >Location: <%= @picture.location%> <br/><br/>
    <medium class="text-muted" ,class="lead" >Caption: <%= @picture.caption %></small>
</h4>

<h4 class="lead">Notes: <%= @picture.body%></h4>
</div>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>

app/views/pictures/update.html.erb
<h1>Pitcures#update</h1>
<p>Find me in app/views/pitcures/update.html.erb</p>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/index.html.erb
<div class="container">
  <% @users.each do |u| 
      userPic = []%>
      <% @pic.each do |pic| %>
                  <% if pic.user_id == u.id %>
                      <% userPic.push(pic.url)%>
                  <% end %>
              <% end %>
  <div class="card bg-light mb-3" style="width: 25rem; height: 25rem; float:left; margin:0px 20px 10px 0px;">
     <img class="card-img-top" src="<%= userPic.first %>" alt="Card image cap">
  <div class="card-body" >
      <h5 class="card-title"><%= link_to(u.name, user_path(u) , {:class => "link-to"})%></h5>
    <p class="card-text"><%= %></p>

  </div>
</div>
<% end %> 
</div>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>

app/views/users/new.html.erb
<div class="container">
<%= form_for @user, :html => {class: 'new_user form-horizontal'} do |f| %>
    <div class="row"><legend class="col-md-4 col-md-offset-4">Create Account:</legend></div>
    <fieldset>
        <div class="form-group">
            <%= f.label :name, 'Name*', class: 'col-md-4 control-label' %>
            <div class="col-md-5">
                <%= f.text_field :name, class: 'form-control' %>
            </div>
        </div>
        <div class="form-group">
            <%= f.label :email, 'Email*', class: 'col-md-4 control-label' %>
            <div class="col-md-5">
                <%= f.text_field :email, class: 'form-control' %>
            </div>
        </div>
        <div class="form-group">
            <%= f.label :password, 'Password*', class: 'col-md-4 control-label' %>
            <div class="col-md-5">
                <%= f.password_field :password, class: 'form-control' %>
            </div>
        </div>
        <div class="form-group">
            <%= f.label :password_confirmation, 'Confirm Password*', class: 'col-md-4 control-label' %>
            <div class="col-md-5">
                <%= f.password_field :password_confirmation, class: 'form-control' %>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-8 col-md-offset-4">
                <%= f.submit 'Create Account', class: 'btn btn-dark'%>
            </div>
        </div>
    </fieldset>
    <% if flash[:danger] %>
    <div class="alert alert-danger">
        <%= flash[:danger] %>
    </div>
<% end %>
<% end %>
</div>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>

app/views/users/show.html.erb
<div class="container">
<h1 class="lead"><%= @user.name %>' Photomap</h1>

<div style="margin:0px 0px 10px 0px;">
<% if @user == current_user %>
    <button type="button" class="btn btn-light" >
        <%= link_to("Add picture", new_user_picture_path(current_user),{:class => "link-to"})%>
    </button>
<% end %>

<% if @user == current_user %>
    <button type="button" class="btn btn-light" style="float:right;">
    <%= link_to("Delete My account", user_path(@user), method: "delete" ,data: {confirm: "Oh no!! We miss you already!"}, :class => "link-to")%>
    </button>
<% end %>
</div>

<% @user.pictures.each do |pic| %>
    <div>
        <%= link_to image_tag(pic.url, height: 'auto', width: '100%'), user_picture_path(@user, pic) %>
        <p class="lead" style="margin:20px 0px 20px 0px;">Location: <%= pic.location %>
        <medium class="text-muted", class="lead">Caption: <%= pic.caption %></small>
        </p>
    </div>       
<% end %>
</div>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>